name: Build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
      - master
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build
    # Set the type of machine to run on
    runs-on: ubuntu-20.04
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.15' # The Go version to download (if necessary) and use.
      - run: go version
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o bin/srun-mac ./cmd/srun
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/srun-linux ./cmd/srun
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/srun.exe ./cmd/srun
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=mipsle go build -o bin/srun-mipsle ./cmd/srun
